packages:
  - 'client'
  - 'server'
allowBuilds:
  '@firebase/util': set this to true or false
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: set this to true or false
  puppeteer: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  zod@3.25.76: patches/zod@3.25.76.patch
