packages:
  - 'client'
  - 'server'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
