
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const FoodSource = {
  TACO: 'TACO',
  USDA_FOUNDATION: 'USDA_FOUNDATION',
  USDA_SR_LEGACY: 'USDA_SR_LEGACY',
  CNF: 'CNF',
  LIVS: 'LIVS',
  OFF: 'OFF',
  MANUAL: 'MANUAL'
} as const

export type FoodSource = (typeof FoodSource)[keyof typeof FoodSource]
